include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - avoid_empty_else
    - prefer_final_fields
    - avoid_print
    - prefer_is_empty
    - prefer_is_not_empty
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - prefer_const_declarations
