name: surbased
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_hooks: ^0.21.2
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
